# src/OC/PlatformBundle/Resources/config/routing.yml# src/OC/PlatformBundle/Resources/config/routing.yml

hello_the_world:
    path:     /hello-world
    defaults: { _controller: OCPlatformBundle:Advert:index }

byebye_world:
    path:     /byebye-world
    defaults: { _controller: OCPlatformBundle:Advert:byebye }